-- -- une vue pour les mots dans des phrases
-- --
-- create view nlp.mot_phrase as
-- select
--     p.debut as phrase_debut,
--     m.*
-- from nlp.mot m
-- join nlp.phrase p on p.texte = m.texte 
-- and p.debut <= m.debut
-- and p.fin >= m.fin;
